apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.csrf_session_key_secret_name }}
  labels:
    {{- include "vada.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.csrf_session_key }}
  vada-csrf-session-key: {{ .Values.csrf_session_key | b64enc | quote }}
  {{- else }}
  vada-csrf-session-key: {{ randAlphaNum 20 | b64enc | quote }}
  {{- end }}
  
---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret_key_secret_name }}
  labels:
    {{- include "vada.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secret_key }}
  vada-secret-key: {{ .Values.secret_key | b64enc | quote }}
  {{- else }}
  vada-secret-key: {{ randAlphaNum 20 | b64enc | quote }}
  {{- end }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.email_password_secret_name }}
  labels:
    {{- include "vada.labels" . | nindent 4 }}
type: Opaque
data:  
  {{- if .Values.email_password }}
  vada-email-password: {{ .Values.email_password | b64enc | quote }}
  {{- end }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db_password_secret_name }}
  labels:
    {{- include "vada.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.db_password }}
  vada-db-password-secret: {{ .Values.db_password | b64enc | quote }}
  {{- else }}
  vada-db-password-secret: {{ randAlphaNum 20 | b64enc | quote }}
  {{- end }}
